### ISSUE TITLE
Start this project

### ISSUE THREAD

**Issue by mapsam** [mapsam/courtney#2]
What do we need to start this project?

- [ ] do the user research over in Lincoln
- [ ] turn user feedback into mockups
- [ ] make code
- [ ] profit

**Comment by mapsam** [comment]
Hey @powersa could you take a look at this and let me know what you think?

**Comment by powersa** [comment]
@mapsam I replied directly from email and I think this looks very good

**Comment by mapsam** [comment]
Excellent.
